spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: schappl
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


springdoc:
  swagger-ui:
    path: ${SPRINGDOC_SWAGGER_UI_PATH}
  api-docs:
    path: /api-docs

server:
  port: 4567

